### PR TITLE
resmgr: Rename cri-resmgr references to nri-resmgr

### PR DESCRIPTION
**Pull request by fmuyassarov**
Most of the code here is coming from the cri-resmgr project. As this repo is not cri-resmgr but rather NRI plugins, we are renaming all the instances of the cri-resmgr here.

All the existing E2E tests of TA have passed (but test05 failed in some runs but not all the time. We need to debug it but I think it can be done separately).

```
Tests summary:
PASS topology-aware/n4c16/test00-basic-placement
PASS topology-aware/n4c16/test01-always-fits
PASS topology-aware/n4c16/test02-shrink-and-grow-shared
PASS topology-aware/n4c16/test03-simple-affinity
PASS topology-aware/n4c16/test04-available-resources
PASS topology-aware/n4c16/test05-reserved-resources
PASS topology-aware/n4c16/test06-fuzz
PASS topology-aware/n4c16/test07-mixed-allocations
PASS topology-aware/n4c16/test09-container-exit
PASS topology-aware/n4c16/test10-additional-reserved-namespaces
PASS topology-aware/n4c16/test11-reserved-cpu-annotations
```

### CODE REVIEW

**Comment by klihub** [comment]
@fmuyassarov Did you regenerate the files which were originally produced by `make generate` (using `code-generator`) or did you manually patch them ? If the latter, can you try running `make generate` and see whether it generates identical files ? Otherwise LGTM.

**Comment by fmuyassarov** [comment]
> @fmuyassarov Did you regenerate the files which were originally produced by `make generate` (using `code-generator`) or did you manually patch them ? If the latter, can you try running `make generate` and see whether it generates identical files ? Otherwise LGTM.


Most of the things are auto-generated. The only few things that were done manually are some method description comments, e2e related stuff, then apiGroup in the adjustment CRD scheme and of course apiGroup renaming in the doc.go which actually resulted on all the auto-generated code being updated. 

So, yes, I ran `make generate` and `make generate-resmgr-api`

**Comment by fmuyassarov** [comment]
@jukkar Please don't merge this PR yet, I seem to found a small issue with the generator. I will update you soon here.

**Comment by fmuyassarov** [comment]
@jukkar I think we are good to go. I noticed that one of the auto generated file was manually updated (`DeepCopyInto()` with it is receiver) otherwise we are not able to build due to compile erro and I noticed that you also had exact same issue in https://github.com/jukkar/nri-resmgr/commit/df7df82c22b12483f2d21269782a35c144c46c23. So, I made the same manual change for now on the zz* file for the DeepCopyInto.

**Comment by jukkar** [comment]
@fmuyassarov yep, I suspect there is a bug in deep copy generation, and we need to manually edit this file after code generation until the bug is fixed.

**Comment by jukkar** [comment]
@fmuyassarov Could you add a prefix to the commit subject, dunno what it could be but one option could be "resmgr: " or you can propose something else too.

**Comment by fmuyassarov** [comment]
> @fmuyassarov Could you add a prefix to the commit subject, dunno what it could be but one option could be "resmgr: " or you can propose something else too.

done

**Review by jukkar — APPROVED** [review]

**Pull request merged**
