### PR TITLE
e2e: Add more balloons tests

### PR DESCRIPTION
**Pull request by jukkar**
Adding missing test02-prometheus and test09-isolated tests from cri-resource-manager repository. This will now pass after the nri-resmgr contains proper infra for instrumentation.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
cc: @fmuyassarov

**Review by fmuyassarov — APPROVED** [review]
LGTM. Shall we keep it on hold until the infra for instrumentation is in place?

**Comment by jukkar** [comment]
Instrumentation infra seems to work ok, at least the two tests pass now. One configmap test (not in this pr) still fails but I am investigating it.

**Comment by jukkar** [comment]
* small refactoring of the common code shared between the tests

**Comment by jukkar** [comment]
The ConfigMap tests work now so this PR includes commits from #49

**Comment by jukkar** [comment]
@klihub + @fmuyassarov ptal

**Comment by fmuyassarov** [comment]
@jukkar In CRI-RM test for test02-prometheus tests, we re-launch the cri-resmgr, do we need it here as well for the NRI-RM or are we going to re-use it from test00/01?

**Comment by jukkar** [comment]
> In CRI-RM test for test02-prometheus tests, we re-launch the cri-resmgr, do we need it here as well for the NRI-RM or are we going to re-use it from test00/01?

Hmm, good point. I had added extra terminate/startup of nri-resmgr which does not seem to be necessary. I will remove it.

**Comment by jukkar** [comment]
@klihub @fmuyassarov PTAL

**Comment by klihub** [comment]
LGTM.

**Review by klihub — APPROVED** [review]
LGTM.

**Review by fmuyassarov — APPROVED** [review]
LGTM

**Pull request merged**
