### PR TITLE
Support self hosted tests

### PR DESCRIPTION
**Pull request by jukkar**
This is a second version of the self hosted runner. It uses a Docker container to execute the self-hosted-runner run.sh script. The e2e VM is created inside the container.
This replaces the #25

### CODE REVIEW

**Review by klihub — APPROVED** [review]
LGTM.

It is seriously good stuff to get this working. Thank you !

**Comment by jukkar** [comment]
Minor tweaks to documentation.

**Comment by jukkar** [comment]
Add a commit that tries to make sure that cilium is working before running the tests.

**Review by fmuyassarov — APPROVED** [review]
LGTM

**Pull request merged**
