### PR TITLE
docs: update TODO.

### PR DESCRIPTION
**Pull request by klihub**
Add TODO-items we discussed F2F last Friday.

### CODE REVIEW

**Comment by klihub** [comment]
@jukkar @kad @fmuyassarov PTAL

**Review by jukkar — APPROVED** [review]
Looks really nice and professional :+1:

**Review by fmuyassarov — COMMENTED** [review]
Looks good and thanks for adding this document @klihub .
Ping @obaranov1 for heads up that we will have this document available here.

**Review by oxxenix — COMMENTED** [review]
thanks

**Pull request merged**
