### PR TITLE
control: remove obsolete controllers.

### PR DESCRIPTION
**Pull request by klihub**
Remove the now obsolete CRI, RDT and blockio controllers. The former requires a CRI connection to the runtime, the latter ones try to directly manipulate/alter containers using goresctrl and the cgroup filesystem. We neither have (the need for) a CRI connection any more nor should we try to do RDT or blockio class resolution and related container manipulation any more. Both of these should be done using corresponding NRI interfaces.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
There are some test functions written for example for blockio controller code in the same package. Are we going to remove those too?

**Comment by klihub** [comment]
> There are some test functions written for example for blockio controller code in the same package. Are we going to remove those too?

Yes, good point. I'll add removing those to this PR.

**Comment by klihub** [comment]
> > There are some test functions written for example for blockio controller code in the same package. Are we going to remove those too?
> 
> Yes, good point. I'll add removing those to this PR.

Actually not the same package, but `pkg/blockio` which needs to be nuked, too. Plus pulling in the packages in `pkg/resmgr/controllers.go`. I totally overlooked those.

**Review by fmuyassarov — COMMENTED** [review]
LGTM

**Review by fmuyassarov — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
