### PR TITLE
intrusive: nuke support for external adjustments.

### PR DESCRIPTION
**Pull request by klihub**
Remove external adjustment CRD and related API along with anything that directly depends on these.

### CODE REVIEW

**Comment by klihub** [comment]
@jukkar @fmuyassarov PTAL

**Review by jukkar — APPROVED** [review]
LGTM

**Review by fmuyassarov — COMMENTED** [review]
LGTM, although too late.

**Comment by fmuyassarov** [comment]
I think (might be wrong) one thing we forgot is to adjust code generation in the https://github.com/jukkar/nri-resmgr/blob/main/scripts/code-generator/generate.sh, because right now running `make generate` will add clientset boilerplate back.

**Pull request merged**
