### PR TITLE
TODO: Add complexity and priority metrics to the task

### PR DESCRIPTION
**Pull request by jukkar**
In order to make a task more understandable, add a complexity estimate into it. The complexity values are defined as C1, C2, C4 and C8. Add also possibility to add a priority to the task with values High (1), Medium (2) and Low (3).

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
cc: @fmuyassarov

**Review by klihub — APPROVED** [review]
LGTM. Not sure about some of the complexity estimates but those can always be adjusted if we notice they're off.

**Review by fmuyassarov — APPROVED** [review]
LGTM

**Comment by jukkar** [comment]
@klihub we can adjust the complexity values right now if you have better idea what they would be, I did mostly guesswork here so they might be way off, and I did not add any priority value (not sure if we need that right now)

**Comment by klihub** [comment]
> @klihub we can adjust the complexity values right now if you have better idea what they would be, I did mostly guesswork here so they might be way off, and I did not add any priority value (not sure if we need that right now)

Well, the ones that stood out are the plugins pkg tree reorg and core NRI Windows support ones being C8. The tree reorg is very very intrusive but I'm not sure if it is really that complex as such. In Windows support there are many unknown for us (what is needed how to really test it, etc.) but at the end of the day, I'm not sure again if what needs to be done is really that complex.

But I think it's fine to leave them like that and update with a better estimate if/once we get a better understanding.

**Pull request merged**
